"""adds board_id to card model

Revision ID: 01168cb290f8
Revises: 39f223ad9946
Create Date: 2023-01-04 10:11:47.113198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01168cb290f8'
down_revision = '39f223ad9946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'board_id')
    # ### end Alembic commands ###
