"""fix relationship between card and board, establish foreighkey in board model

Revision ID: 06200f264f09
Revises: 604b912eb19b
Create Date: 2023-01-04 14:39:53.527861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06200f264f09'
down_revision = '604b912eb19b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('card_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('delete_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.add_column('board', sa.Column('card_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'board', 'card', ['card_id'], ['card_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board', type_='foreignkey')
    op.drop_column('board', 'card_id')
    op.drop_table('card')
    # ### end Alembic commands ###
