"""add Card and Board models

Revision ID: 16f42ee1106e
Revises: 
Create Date: 2023-01-03 04:07:23.425117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f42ee1106e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('card_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('card', 'liked')
    op.drop_column('card', '\u2003card_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('\u2003card_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('card', sa.Column('liked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('card', 'card_id')
    # ### end Alembic commands ###
