"""empty message

Revision ID: 27fce041b3b3
Revises: a061146463b2
Create Date: 2023-01-18 17:00:34.354013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27fce041b3b3'
down_revision = 'a061146463b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('card_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'card_color')
    # ### end Alembic commands ###
