"""added one board to many card relationship

Revision ID: 353121078d96
Revises: f644da1230b4
Create Date: 2023-01-03 14:17:49.890185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353121078d96'
down_revision = 'f644da1230b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'board_id')
    # ### end Alembic commands ###
