"""added print_2

Revision ID: 43289375bf32
Revises: 50aedd2f44c8
Create Date: 2023-01-17 07:45:16.381708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43289375bf32'
down_revision = '50aedd2f44c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    # ### end Alembic commands ###
