"""empty message

Revision ID: 484b20184830
Revises: 5f81132c844f
Create Date: 2023-06-26 13:37:42.054816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484b20184830'
down_revision = '5f81132c844f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'board_id')
    # ### end Alembic commands ###
