"""added print_1

Revision ID: 50aedd2f44c8
Revises: 3366d814406a
Create Date: 2023-01-17 07:39:59.723254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50aedd2f44c8'
down_revision = '3366d814406a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('card_board_id_fkey', 'card', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('card_board_id_fkey', 'card', 'board', ['board_id'], ['board_id'])
    # ### end Alembic commands ###
