"""Add user model.

Revision ID: 5a37a6b68025
Revises: d5010cb4d5f9
Create Date: 2023-01-06 13:04:49.634842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a37a6b68025'
down_revision = 'd5010cb4d5f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('board', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'board', 'user', ['owner_id'], ['id'])
    op.add_column('card', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'owner_id')
    op.drop_constraint(None, 'board', type_='foreignkey')
    op.drop_column('board', 'owner_id')
    op.drop_table('user')
    # ### end Alembic commands ###
