"""empty message

Revision ID: 621855356841
Revises: 899dd28acf1a
Create Date: 2023-01-05 10:26:05.789409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621855356841'
down_revision = '899dd28acf1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'board_id')
    # ### end Alembic commands ###
