"""fixed comma in board

Revision ID: 8672f1402671
Revises: f7eb21e1a4ef
Create Date: 2023-01-03 10:47:09.855389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8672f1402671'
down_revision = 'f7eb21e1a4ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('owner', sa.String(), nullable=True))
    op.add_column('card', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'likes')
    op.drop_column('board', 'owner')
    # ### end Alembic commands ###
