"""empty message

Revision ID: 8fd1bfdc8992
Revises: 
Create Date: 2023-01-05 10:55:39.679970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd1bfdc8992'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('title', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=True),
                    sa.Column('owner', sa.VARCHAR(length=20),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='boards_pkey')
                    )
    op.create_table('cards',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.Column('like_count', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('board_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['board_id'], ['boards.id'], name='cards_board_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='cards_pkey')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    op.drop_table('boards')
    # ### end Alembic commands ###
