"""empty message

Revision ID: 922a3ac064a7
Revises: 6551a157980e
Create Date: 2023-01-04 14:19:13.958154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922a3ac064a7'
down_revision = '6551a157980e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('board', 'board_id')
    op.drop_constraint('card_board_id_fkey', 'card', type_='foreignkey')
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.create_foreign_key('card_board_id_fkey', 'card', 'board', ['board_id'], ['board_id'])
    op.add_column('board', sa.Column('board_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('board', 'id')
    # ### end Alembic commands ###
