"""Update card owner to author

Revision ID: a061146463b2
Revises: 5a37a6b68025
Create Date: 2023-01-17 14:18:46.372253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a061146463b2'
down_revision = '5a37a6b68025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('card_owner_id_fkey', 'card', type_='foreignkey')
    op.create_foreign_key(None, 'card', 'user', ['author_id'], ['id'])
    op.drop_column('card', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.create_foreign_key('card_owner_id_fkey', 'card', 'user', ['owner_id'], ['id'])
    op.drop_column('card', 'author_id')
    # ### end Alembic commands ###
