"""empty message

Revision ID: a1feb4679203
Revises: ca4e74082b35
Create Date: 2023-01-19 15:34:51.080610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1feb4679203'
down_revision = 'ca4e74082b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('likescount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'likescount')
    # ### end Alembic commands ###
