"""Changes

Revision ID: c90a87e94a9a
Revises: 
Create Date: 2023-01-04 12:59:58.480619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90a87e94a9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_table',
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('board_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('owners_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('board_id', name='board_table_pkey')
    )
    # ### end Alembic commands ###
