"""added liked column to database

Revision ID: cdcccc87f2f2
Revises: 16f42ee1106e
Create Date: 2023-01-03 05:14:06.445028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcccc87f2f2'
down_revision = '16f42ee1106e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('liked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'liked')
    # ### end Alembic commands ###
