<<<<<<<< HEAD:migrations/versions/d112e7e98248_recreate_database.py
"""recreate database

Revision ID: d112e7e98248
Revises: 
Create Date: 2023-01-06 13:20:31.020540
========
"""recreated database

Revision ID: d63e97efafdc
Revises: 
Create Date: 2023-01-06 11:02:42.616683
>>>>>>>> df9695881055b0a24816cead9dc9fe5205f65a48:migrations/versions/d63e97efafdc_recreated_database.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/d112e7e98248_recreate_database.py
revision = 'd112e7e98248'
========
revision = 'd63e97efafdc'
>>>>>>>> df9695881055b0a24816cead9dc9fe5205f65a48:migrations/versions/d63e97efafdc_recreated_database.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('board_id')
    )
    op.create_table('card',
    sa.Column('card_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.board_id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    op.drop_table('board')
    # ### end Alembic commands ###
