"""updated card model attribute message to be STRING(40)

Revision ID: e5c4bb1f124d
Revises: 7eb3dbac3da3
Create Date: 2023-01-05 19:17:52.460935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c4bb1f124d'
down_revision = '7eb3dbac3da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'message',
               existing_type=sa.String(length=40),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
